### ISSUE TITLE
load pickle file not found

### ISSUE THREAD

**Issue by alvi68** [levindoneto/lanGen#8]
File "E:\reserch 222\ngram\management\FileManagement.py", line 32, in loadPickleData
    with open(filePath, "rb") as fb:

OSError: [Errno 22] Invalid argument: 'in.pickle]|-'

could not found the file .pickle

**Comment by levindoneto** [comment]
@alvi68 since you have not created the pickle file, at the first time you should use
```python
lm (-n 1 -s in.pickle)
````
in order to save the incoming data to the pickle file `in` and avoid this error.

Eventually, I'm gonna handle this error in order to avoid this kinda problem during the execution.
